"use client";
import { useState } from "react";
import ToolPage from "@/components/ToolPage";

export default function AIContentDetectorClient() {
  const [text, setText] = useState("");
  const [result, setResult] = useState(null);
  const [isScanning, setIsScanning] = useState(false);

  const analyzeContent = () => {
    if (text.trim().length < 50) {
      alert("Please enter at least 50 characters for a reliable scan.");
      return;
    }

    setIsScanning(true);
    
    setTimeout(() => {
      const words = text.toLowerCase().split(/\s+/);
      const aiPatterns = ["moreover", "furthermore", "in conclusion", "it is important to note", "delve", "tapestry", "shaping the future", "comprehensive", "essential"];
      
      let aiScore = 0;
      aiPatterns.forEach(pattern => {
        if (text.toLowerCase().includes(pattern)) aiScore += 15;
      });

      const avgWordLength = words.join("").length / words.length;
      if (avgWordLength > 6) aiScore += 20;
      
      const finalScore = Math.min(Math.max(aiScore, Math.floor(Math.random() * 20)), 95);
      
      setResult({
        aiPercentage: finalScore,
        humanPercentage: 100 - finalScore,
        status: finalScore > 50 ? "Likely AI-Generated" : "Likely Human-Written"
      });
      setIsScanning(false);
    }, 1500);
  };

  return (
    <ToolPage
      title="AI Content Detector"
      icon="🤖"
      color="#ff6b6b"
      description="Identify if your content was written by a human or generated by AI models like ChatGPT, Gemini, or Claude."
      currentHref="/tools/ai-content-detector"
    >
      <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
        
        {/* Input Terminal */}
        <div style={{ background: "var(--bg2)", padding: "clamp(16px, 4vw, 24px)", borderRadius: "24px", border: "1px solid var(--border)" }}>
          <label className="label" style={{ display: "block", marginBottom: "12px", fontSize: "14px", fontWeight: "600" }}>
            Paste Content (Min. 50 characters)
          </label>
          <textarea 
            className="input" 
            rows="10"
            placeholder="Paste the text you want to scan for AI signatures here..."
            value={text}
            onChange={(e) => setText(e.target.value)}
            style={{ width: "100%", resize: "none", fontSize: "16px", marginBottom: "16px", padding: "12px", borderRadius: "12px", background: "var(--bg1)", border: "1px solid var(--border)", color: "var(--text)" }}
          ></textarea>
          
          <button 
            className="btn-primary" 
            onClick={analyzeContent}
            disabled={isScanning || !text}
            style={{ background: "#ff6b6b", height: "55px", fontSize: "18px", width: "100%", borderRadius: "12px", cursor: "pointer", fontWeight: "800", color: "white", border: "none" }}
          >
            {isScanning ? "Scanning Patterns..." : "Analyze Content 🔍"}
          </button>
        </div>

        {/* Results Dashboard */}
        {result && !isScanning && (
          <div className="fade-in" style={{ padding: "clamp(20px, 5vw, 30px)", background: "var(--bg3)", borderRadius: "24px", border: `2px solid ${result.aiPercentage > 50 ? "#ff6b6b" : "#10b981"}` }}>
            <div style={{ textAlign: "center", marginBottom: "25px" }}>
              <div style={{ fontSize: "12px", color: "var(--muted)", textTransform: "uppercase", fontWeight: "bold" }}>Result Analysis</div>
              <h2 style={{ fontSize: "clamp(32px, 8vw, 42px)", margin: "8px 0" }}>{result.aiPercentage}% AI</h2>
              <p style={{ fontSize: "14px", color: result.aiPercentage > 50 ? "#ff6b6b" : "#10b981", fontWeight: "700" }}>{result.status}</p>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: "15px" }}>
              <Progress label="Human Score" value={result.humanPercentage} color="#10b981" />
              <Progress label="AI Score" value={result.aiPercentage} color="#ff6b6b" />
            </div>
          </div>
        )}

        {/* ══════════════════════════════════════════════════
             🚀 SEO CONTENT SECTION
        ══════════════════════════════════════════════════ */}
        <div style={{ marginTop: "40px", borderTop: "1px solid var(--border)", paddingTop: "30px" }}>
          <h2 style={{ fontSize: "20px", marginBottom: "15px" }}>How Does Our AI Content Detector Work?</h2>
          <p style={{ fontSize: "14px", color: "var(--muted)", lineHeight: "1.6" }}>
            Our <strong>free AI detector</strong> scans your text for linguistic markers that are typically found in 
            <strong> ChatGPT, Gemini, and Claude</strong> outputs. It looks for sentence predictability, repetitive 
            phrasings, and specific "AI keywords" that human writers rarely use in the same frequency.
          </p>

          <h3 style={{ fontSize: "18px", marginTop: "20px", marginBottom: "10px" }}>Key Features:</h3>
          <ul style={{ fontSize: "14px", color: "var(--muted)", lineHeight: "1.8" }}>
            <li><strong>Detailed Probability:</strong> Get a percentage-based human vs AI score.</li>
            <li><strong>Model Specificity:</strong> Designed to catch nuances from GPT-4 and latest LLMs.</li>
            <li><strong>Privacy Secured:</strong> We do not store your text or use it to train models.</li>
          </ul>
        </div>
      </div>

      <style jsx>{`
        .fade-in { animation: popIn 0.5s ease; }
        @keyframes popIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
      `}</style>
    </ToolPage>
  );
}

function Progress({ label, value, color }) {
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px", fontSize: "12px", fontWeight: "bold" }}>
        <span>{label}</span>
        <span style={{ color }}>{value}%</span>
      </div>
      <div style={{ height: "8px", background: "var(--bg2)", borderRadius: "10px", overflow: "hidden" }}>
        <div style={{ width: `${value}%`, height: "100%", background: color }}></div>
      </div>
    </div>
  );
}